exports.CREATE_USER = 'CREATE_USER';
exports.UPDATE_USER = 'UPDATE_USER';
exports.DELETE_USER = 'DELETE_USER';

exports.CREATE_ROLE = 'CREATE_ROLE';
exports.UPDATE_ROLE = 'UPDATE_ROLE';
exports.DELETE_ROLE = 'DELETE_ROLE';

exports.CREATE_APP = 'CREATE_APP';
exports.UPDATE_APP = 'UPDATE_APP';
exports.DELETE_APP = 'DELETE_APP';

exports.CREATE_FACTORY = 'CREATE_FACTORY';
exports.UPDATE_FACTORY = 'UPDATE_FACTORY';
exports.DELETE_FACTORY = 'DELETE_FACTORY';

exports.CREATE_PROJECT_TYPE = 'CREATE_PROJECT_TYPE';
exports.UPDATE_PROJECT_TYPE = 'UPDATE_PROJECT_TYPE';
exports.DELETE_PROJECT_TYPE = 'DELETE_PROJECT_TYPE';

exports.CREATE_BUSINESS_UNIT = 'CREATE_BUSINESS_UNIT';
exports.UPDATE_BUSINESS_UNIT = 'UPDATE_BUSINESS_UNIT';
exports.DELETE_BUSINESS_UNIT = 'DELETE_BUSINESS_UNIT';

exports.CREATE_COMPANY = 'CREATE_COMPANY';
exports.UPDATE_COMPANY = 'UPDATE_COMPANY';
exports.DELETE_COMPANY = 'DELETE_COMPANY';

exports.CREATE_CURRENCY = 'CREATE_CURRENCY';
exports.UPDATE_CURRENCY = 'UPDATE_CURRENCY';
exports.DELETE_CURRENCY = 'DELETE_CURRENCY';

exports.CREATE_CURRENCY_EXCHANGE_RATE = 'CREATE_CURRENCY_EXCHANGE_RATE';
exports.UPDATE_CURRENCY_EXCHANGE_RATE = 'UPDATE_CURRENCY_EXCHANGE_RATE';
exports.DELETE_CURRENCY_EXCHANGE_RATE = 'DELETE_CURRENCY_EXCHANGE_RATE';