//authentication
exports.USER_AUTHENTICATED = 'USER_AUTHENTICATED';
exports.NO_GAUTH_TOKEN ='NO_GAUTH_TOKEN';
exports.NO_GAUTH_CODE ='NO_GAUTH_CODE';
exports.NO_USERNAME_OR_PASSWORD ='NO_USERNAME_OR_PASSWORD';
exports.FIND_USER_FAILED = 'FIND_USER_FAILED';
exports.USER_NOT_ACTIVE = 'USER_NOT_ACTIVE';
exports.USER_UNAUTHORIZED = 'USER_UNAUTHORIZED';
exports.INVALID_OTP = 'INVALID_OTP';
exports.EXPIRED_OTP = 'EXPIRED_OTP';

exports.USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
exports.USER_CREATE_FAILED = 'USER_CREATE_FAILED';
exports.USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
exports.USER_UPDATE_FAILED = 'USER_UPDATE_FAILED';
exports.FETCH_USER_FAILED = 'FETCH_USER_FAILED';
exports.FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
exports.USER_DELETE_FAILED = 'USER_DELETE_FAILED';
exports.USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
exports.USER_NOT_FOUND = 'USER_NOT_FOUND';
exports.USER_ACKNOWLEDGE_SUCCESS = 'USER_ACKNOWLEDGE_SUCCESS';
exports.USER_ACKNOWLEDGE_FAILED = 'USER_ACKNOWLEDGE_FAILED';
exports.UNAUTHORIZED_ROLE_ACCESS = 'UNAUTHORIZED_ROLE_ACCESS';

//Roles
exports.ROLE_CREATE_SUCCESS = 'ROLE_CREATE_SUCCESS';
exports.ROLE_CREATE_FAILED = 'ROLE_CREATE_FAILED';
exports.ROLE_UPDATE_SUCCESS = 'ROLE_UPDATE_SUCCESS';
exports.ROLE_UPDATE_FAILED = 'ROLE_UPDATE_FAILED';
exports.FETCH_ROLE_FAILED = 'FETCH_ROLE_FAILED';
exports.FETCH_ROLE_SUCCESS = 'FETCH_ROLE_SUCCESS';
exports.ROLE_DELETE_FAILED = 'ROLE_DELETE_FAILED';
exports.ROLE_DELETE_SUCCESS = 'ROLE_DELETE_SUCCESS';


//Warehouse
exports.WAREHOUSE_CREATE_SUCCESS = 'WAREHOUSE_CREATE_SUCCESS';
exports.WAREHOUSE_CREATE_FAILED = 'WAREHOUSE_CREATE_FAILED';
exports.WAREHOUSE_UPDATE_SUCCESS = 'WAREHOUSE_UPDATE_SUCCESS';
exports.WAREHOUSE_UPDATE_FAILED = 'WAREHOUSE_UPDATE_FAILED';
exports.FETCH_WAREHOUSE_FAILED = 'FETCH_WAREHOUSE_FAILED';
exports.FETCH_WAREHOUSE_SUCCESS = 'FETCH_WAREHOUSE_SUCCESS';
exports.WAREHOUSE_DELETE_FAILED = 'WAREHOUSE_DELETE_FAILED';
exports.WAREHOUSE_DELETE_SUCCESS = 'WAREHOUSE_DELETE_SUCCESS';
