const RESTRICTED_ROLES = {
    MDM_SUPER_USER: 'MDM_SUPER_USER',
    ADMINV2: 'ADMINV2',
    MDM: 'MDM',
    ADMIN: 'ADMIN'
};

const ROLE_ACCESS_MAPPER = {
    [RESTRICTED_ROLES.MDM_SUPER_USER]: [RESTRICTED_ROLES.MDM, RESTRICTED_ROLES.MDM_SUPER_USER],
    [RESTRICTED_ROLES.ADMINV2]: [RESTRICTED_ROLES.ADMINV2],
    [RESTRICTED_ROLES.ADMIN]: [RESTRICTED_ROLES.ADMIN]
};

module.exports = { RESTRICTED_ROLES, ROLE_ACCESS_MAPPER };
